"""Auto-generate AGOL item thumbnails from canonical library files.

AGOL items support a small thumbnail image (~300×200 PNG) shown in
content browser, gallery views, and search results. A blank thumbnail
makes items look unfinished — and AGOL's autogenerated thumbnails
(when present at all) tend to be a generic map preview that doesn't
reflect the dataset's character.

This module generates a functional thumbnail per dataset:

* **Vectors** → render the bbox + any visible features as a light
  outline against a neutral background. Uses geopandas + matplotlib.
* **Rasters** → render a decimated grayscale preview (continuous) or
  palette preview (categorical). Uses rasterio + matplotlib.

Thumbnails are cached at ``.y2y/thumbnails/<dataset_id>.png`` keyed
by ``checksum_sha256`` — re-generated only when the catalogue's
recorded checksum changes (i.e., the source file actually changed).

The push() flow in ``pipeline.agol_sync`` calls
``generate_thumbnail()`` right before uploading; uploads pass the
returned Path to ``Item.update(thumbnail=...)``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import matplotlib

# Use the non-interactive backend so this module doesn't try to open
# a GUI window on headless CI / scheduled-job runs.
matplotlib.use("Agg")

import matplotlib.pyplot as plt  # noqa: E402  — must come after use("Agg")
import numpy as np  # noqa: E402


THUMBNAIL_WIDTH_PX = 300
THUMBNAIL_HEIGHT_PX = 200
THUMBNAIL_DPI = 100

_CACHE_DIR_NAME = "thumbnails"
_CHECKSUM_SIDECAR_SUFFIX = ".sha256"


class ThumbnailError(RuntimeError):
    """Raised when a thumbnail cannot be generated for a row.

    The push() flow catches this and falls back to no-thumbnail
    upload rather than failing the whole push.
    """


# ----------------------------------------------------------------------------
# Public API
# ----------------------------------------------------------------------------

def generate_thumbnail(
    row: dict[str, Any],
    library_root: Path,
    cache_dir: Path,
) -> Path:
    """Produce (and cache) a thumbnail PNG for one dataset row.

    Args:
        row: Catalogue row dict. Must carry ``dataset_id``,
            ``file_path``, ``classification``, and ``checksum_sha256``.
        library_root: The typed library root (``library/spatial``).
            ``row['file_path']`` is resolved relative to this.
        cache_dir: Directory where ``.y2y/thumbnails/`` should live
            (typically ``.y2y`` under the project root). Created if
            absent.

    Returns:
        Path to a PNG (always 300×200 unless the renderer had to
        bail and used a fallback aspect).

    Cache hit: if a PNG already exists at the cache path AND a
    sidecar ``.sha256`` file records the same checksum as the row's
    current ``checksum_sha256``, returns immediately without
    re-rendering.

    Raises:
        ThumbnailError: when the underlying source file can't be
            read or the classification value doesn't map to a known
            renderer.
    """
    dataset_id = row.get("dataset_id")
    if not dataset_id:
        raise ThumbnailError("row has no dataset_id; cannot generate thumbnail")

    classification = row.get("classification")
    checksum = row.get("checksum_sha256") or ""
    file_path = row.get("file_path")
    if not file_path:
        raise ThumbnailError(
            f"row {dataset_id!r} has no file_path; cannot generate thumbnail"
        )

    source = library_root / file_path
    if not source.exists():
        raise ThumbnailError(
            f"source file not found for thumbnail: {source}"
        )

    thumbs_dir = Path(cache_dir) / _CACHE_DIR_NAME
    thumbs_dir.mkdir(parents=True, exist_ok=True)
    out_path = thumbs_dir / f"{dataset_id}.png"
    sidecar = out_path.with_suffix(out_path.suffix + _CHECKSUM_SIDECAR_SUFFIX)

    # Cache hit: same checksum, PNG already on disk.
    if out_path.exists() and sidecar.exists():
        if sidecar.read_text(encoding="utf-8").strip() == checksum:
            return out_path

    # Cache miss → render.
    if classification == "vector":
        _render_vector_thumbnail(source, out_path)
    elif classification in ("continuous", "categorical"):
        _render_raster_thumbnail(source, classification, out_path)
    else:
        raise ThumbnailError(
            f"unsupported classification {classification!r} for "
            f"thumbnail rendering"
        )

    sidecar.write_text(checksum, encoding="utf-8")
    return out_path


# ----------------------------------------------------------------------------
# Vector renderer
# ----------------------------------------------------------------------------

def _render_vector_thumbnail(source: Path, out_path: Path) -> None:
    """Render a vector dataset as a thumbnail PNG.

    Loads the features, draws them in dark grey against a light grey
    background. Lines and outlines are 0.6 pt to stay legible at
    thumbnail scale. Filled polygons get a light fill so dense
    coverage still reads correctly. Points are rendered as small
    dots.

    Falls back to a bbox-only outline if the geometry is too dense
    to render in <2 s (e.g., a multi-million-feature road network).
    """
    import geopandas as gpd
    from shapely.geometry.base import BaseGeometry  # noqa: F401 — typing only

    try:
        gdf = gpd.read_file(source)
    except Exception as exc:
        raise ThumbnailError(f"failed to read {source}: {exc}") from exc

    if gdf.empty:
        # Render an empty bbox so the steward sees something.
        _render_empty_placeholder(out_path, "empty dataset")
        return

    fig, ax = _make_figure()
    ax.set_facecolor("#f5f5f5")

    # Draw the actual geometry. Polygon fills are light; lines/points
    # are dark.
    geom_type = gdf.geom_type.iloc[0] if not gdf.empty else None
    try:
        if "Polygon" in str(geom_type):
            gdf.plot(
                ax=ax,
                color="#cfd8dc",     # light fill
                edgecolor="#37474f", # dark outline
                linewidth=0.6,
            )
        elif "Line" in str(geom_type):
            gdf.plot(ax=ax, color="#37474f", linewidth=0.6)
        else:
            # Point / MultiPoint / mixed — small markers.
            gdf.plot(ax=ax, color="#37474f", markersize=3)
    except Exception:
        # Rendering failed (huge dataset, unusual geometry).
        # Fall back to a bbox-only outline.
        bounds = gdf.total_bounds  # (minx, miny, maxx, maxy)
        _draw_bbox_outline(ax, bounds)

    _finish_figure(ax, fig, out_path)


# ----------------------------------------------------------------------------
# Raster renderer
# ----------------------------------------------------------------------------

def _render_raster_thumbnail(
    source: Path,
    classification: str,
    out_path: Path,
) -> None:
    """Render a raster dataset as a thumbnail PNG.

    Reads at a coarse decimation (target = ~600×400 source pixels,
    then matplotlib downsizes to 300×200 final). Masks the source's
    NoData. Continuous classifications use ``viridis`` (perceptually
    uniform); categorical uses ``tab20`` with the integer class
    codes mapped to discrete colours.
    """
    import rasterio
    from rasterio.enums import Resampling

    try:
        with rasterio.open(source) as ds:
            # Decimate aggressively for thumbnail rendering.
            scale = max(
                ds.width / (THUMBNAIL_WIDTH_PX * 2),
                ds.height / (THUMBNAIL_HEIGHT_PX * 2),
                1.0,
            )
            out_w = max(1, int(ds.width / scale))
            out_h = max(1, int(ds.height / scale))
            arr = ds.read(
                1,
                out_shape=(out_h, out_w),
                resampling=(
                    Resampling.average
                    if classification == "continuous"
                    else Resampling.nearest
                ),
            )
            nodata = ds.nodata
    except Exception as exc:
        raise ThumbnailError(f"failed to read raster {source}: {exc}") from exc

    # Mask nodata so the colour ramp ignores it.
    masked = arr.astype("float64", copy=True)
    if nodata is not None:
        if np.issubdtype(arr.dtype, np.floating):
            mask = (arr <= -1e30) | (arr == nodata)
        else:
            mask = arr == nodata
    else:
        mask = np.zeros_like(arr, dtype=bool)
    masked[mask] = np.nan

    fig, ax = _make_figure()
    ax.set_facecolor("#f5f5f5")

    if classification == "continuous":
        ax.imshow(masked, cmap="viridis", interpolation="nearest")
    else:  # categorical
        # Use a discrete colormap. tab20 handles up to 20 classes
        # cleanly; for >20-class rasters falls back to a continuous
        # palette which is fine for thumbnail purposes.
        valid = masked[~np.isnan(masked)]
        n_classes = int(np.unique(valid).size) if valid.size else 0
        cmap = "tab20" if n_classes <= 20 else "viridis"
        ax.imshow(masked, cmap=cmap, interpolation="nearest")

    _finish_figure(ax, fig, out_path)


# ----------------------------------------------------------------------------
# Shared figure helpers
# ----------------------------------------------------------------------------

def _make_figure():
    """Build a 300×200 figure with no axes / spines / margins."""
    width_in = THUMBNAIL_WIDTH_PX / THUMBNAIL_DPI
    height_in = THUMBNAIL_HEIGHT_PX / THUMBNAIL_DPI
    fig, ax = plt.subplots(figsize=(width_in, height_in), dpi=THUMBNAIL_DPI)
    ax.set_aspect("equal")
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)
    fig.subplots_adjust(left=0, right=1, bottom=0, top=1)
    return fig, ax


def _finish_figure(ax, fig, out_path: Path) -> None:
    """Tighten margins, save PNG, close figure."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(
        out_path,
        dpi=THUMBNAIL_DPI,
        bbox_inches="tight",
        pad_inches=0,
        facecolor=ax.get_facecolor(),
    )
    plt.close(fig)


def _draw_bbox_outline(ax, bounds: tuple[float, float, float, float]) -> None:
    """Draw a dashed rectangle of the bounds — used as a fallback."""
    minx, miny, maxx, maxy = bounds
    ax.plot(
        [minx, maxx, maxx, minx, minx],
        [miny, miny, maxy, maxy, miny],
        color="#37474f",
        linewidth=0.6,
        linestyle="--",
    )
    ax.set_xlim(minx, maxx)
    ax.set_ylim(miny, maxy)


def _render_empty_placeholder(out_path: Path, label: str) -> None:
    """Render a plain placeholder for edge cases (empty geometry, etc.)."""
    fig, ax = _make_figure()
    ax.set_facecolor("#f5f5f5")
    ax.text(
        0.5, 0.5, label,
        ha="center", va="center",
        transform=ax.transAxes,
        color="#90a4ae",
        fontsize=10,
    )
    _finish_figure(ax, fig, out_path)
